name: 'Deploy Organization Actions'
description: 'This repo contains all of our Github Actions we want to use in our Organization and the ability to publish them to all repos in the Organization.'
inputs:
  org_id:
    description: 'The ID of the Organization containing all of the repositories you want to deploy your actions to.  Can be found in your Organization page url (https://github.com/<org_id>)'
    required: true
  action_file_names:
    description: 'The file names of all github account that can be found at the root of this Organization that you want to deploy to all repos in the Organization'
    required: true
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
branding:
  icon: 'triangle'
  color: 'green'
runs:
  using: 'node16'
  main: 'index.js'
