name: 'Deploy Project Actions'
description: 'This repo contains all of our Github Actions we want to use in our project and the ability to publish them to all repos in the project.'
inputs:
  org_id:
    description: 'The ID of the Organization containing all of the repositories you want to deploy your actions to.  Can be found in your Organization page url (https://github.com/<org_id>)'
    required: true
  team_id:
    description: 'The ID of the Team that has access to all of the repositories you want to deploy your actions to.  Can be found in your Organization Teams page url (https://github.com/orgs/<org_id>/teams/<team_id>)'
    required: true
  action_file_names:
    description: 'The file names of all github acount that can be found at the root of this project that you want to deploy to all repos in the project'
    required: true
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
branding:
  icon: 'triangle'  
  color: 'green'
runs:
  using: 'node12'
  main: 'index.js'
