# This workflow will run on merge of a PR or push to master
# It will run the integration developement checklist and if that passes
# creates a new release with the Release and Tag name both being the 
# package.json version and will with a created tgz file and the SHA256 has in the release body


name: Release Current Version

on:
  push:
    branches: [ master, main ]

jobs:
  release-current-version-12:
    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 12.22.12
    - name: Get NPM Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@95bc31c6dd3145896c110e382f840bb1e750d09c
    - name: Create Build
      id: create_build
      run: |
        npm ci &&
        cd .. && 
        tar --exclude="./${{ github.event.repository.name }}/.git" --exclude="./${{ github.event.repository.name }}/.gitignore" --exclude="./${{ github.event.repository.name }}/.github" -czvf "${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-12.22.12.tgz" "./${{ github.event.repository.name }}" &&  
        echo "::set-output name=build_hash::$(sha256sum '${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-12.22.12.tgz' | grep -oE '^[^ ]*' )" &&
        cd ${{ github.event.repository.name }}
    - name: Polarity Integration Development Checklist
      id: int-dev-checklist
      uses: polarityio/polarity-integration-development-checklist@v1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Generate changelog #Was undefined
    #   id: release-notes
    #   uses: metcalfc/changelog-generator@v4.0.1
    #   with:
    #     myToken: ${{ secrets.GITHUB_TOKEN }}
    #     # TODO Fix
    # - name: Release Changelog Builder
    #   id: release-notes
    #   uses: mikepenz/release-changelog-builder-action@v3.5.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Versioned Release
      id: create_versioned_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.package-version.outputs.current-version}}
        release_name: ${{steps.package-version.outputs.current-version}}
        body: |
          # Release Notes
          ${{steps.release-notes.outputs.changelog}}
          # Downloads

          **Polarity Server 4.2.x**
          - DOWNLOAD: [${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-12.22.12.tgz](https://github.com/polarityio/${{ github.event.repository.name }}/releases/download/${{ steps.package-version.outputs.current-version }}/${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-12.22.12.tgz)
          SHA256: ${{ steps.create_build.outputs.build_hash }}
          - DOWNLOAD: [${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-14.21.1.tgz](https://github.com/polarityio/${{ github.event.repository.name }}/releases/download/${{ steps.package-version.outputs.current-version }}/${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-14.21.1.tgz)
          SHA256: ${{ steps.create_build.outputs.build_hash }}
          - DOWNLOAD: [${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-18.12.1.tgz](https://github.com/polarityio/${{ github.event.repository.name }}/releases/download/${{ steps.package-version.outputs.current-version }}/${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-18.12.1.tgz)
          SHA256: ${{ steps.create_build.outputs.build_hash }}
        draft: false
        prerelease: false
    - name: Add Release Url for Next Jobs
      run: |
        echo "${{ steps.create_versioned_release.outputs.upload_url }}" > newReleaseUploadUrl.txt
    - name: Upload newReleaseUploadUrl for Version 14 & 18 Jobs
      uses: actions/upload-artifact@v3
      with:
        name: newReleaseUploadUrl
        path: newReleaseUploadUrl.txt
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_versioned_release.outputs.upload_url }} 
        asset_path: ../${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-12.22.12.tgz
        asset_name: ${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-12.22.12.tgz
        asset_content_type: application/gzip

  release-current-version-14:
    runs-on: ubuntu-latest
    container: 'centos:7'
    needs: release-current-version-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14.21.1
    - name: Get NPM Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@95bc31c6dd3145896c110e382f840bb1e750d09c
    - name: Create Build
      id: create_build
      run: |
        npm ci &&
        cd .. && 
        tar --exclude="./${{ github.event.repository.name }}/.git" --exclude="./${{ github.event.repository.name }}/.gitignore" --exclude="./${{ github.event.repository.name }}/.github" -czvf "${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-14.21.1.tgz" "./${{ github.event.repository.name }}" &&  
        echo "::set-output name=build_hash::$(sha256sum '${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-14.21.1.tgz' | grep -oE '^[^ ]*' )" &&
        cd ${{ github.event.repository.name }}
    - name: Download newReleaseUploadUrl
      uses: actions/download-artifact@v3
      with:
        name: newReleaseUploadUrl
    - name: Add newReleaseUploadUrl to ENV for use
      run: |
        value=`cat newReleaseUploadUrl.txt`
        echo "newReleaseUploadUrl=$value" >> $GITHUB_ENV
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.newReleaseUploadUrl }} 
        asset_path: ../${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-14.21.1.tgz
        asset_name: ${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-14.21.1.tgz
        asset_content_type: application/gzip
  
  release-current-version-18:
    runs-on: ubuntu-latest
    container: 'centos:8' #Node 18 doesn't seem like it can run on centos 7
    needs: release-current-version-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
    - name: Get NPM Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@95bc31c6dd3145896c110e382f840bb1e750d09c
    - name: Create Build
      id: create_build
      run: |
        npm ci &&
        cd .. && 
        tar --exclude="./${{ github.event.repository.name }}/.git" --exclude="./${{ github.event.repository.name }}/.gitignore" --exclude="./${{ github.event.repository.name }}/.github" -czvf "${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-18.12.1.tgz" "./${{ github.event.repository.name }}" &&  
        echo "::set-output name=build_hash::$(sha256sum '${{ github.event.repository.name }}-${{ steps.package-version.outputs.current-version }}+node-18.12.1.tgz' | grep -oE '^[^ ]*' )" &&
        cd ${{ github.event.repository.name }}
    - name: Download newReleaseUploadUrl
      uses: actions/download-artifact@v3
      with:
        name: newReleaseUploadUrl
    - name: Add newReleaseUploadUrl to ENV for use
      run: |
        value=`cat newReleaseUploadUrl.txt`
        echo "newReleaseUploadUrl=$value" >> $GITHUB_ENV
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.newReleaseUploadUrl }} 
        asset_path: ../${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-18.12.1.tgz
        asset_name: ${{ github.event.repository.name }}-${{steps.package-version.outputs.current-version}}+node-18.12.1.tgz
        asset_content_type: application/gzip